# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "slurm"

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus = 1
    libvirt.qemu_use_session = false
  end

  config.vm.box = "almalinux/8"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.network :private_network, :ip => "192.168.124.25"

  config.vm.provision "ansible" do |ansible|
    ansible.raw_ssh_args = ['-o UserKnownHostsFile=/dev/null']
    ansible.host_key_checking = false
    #ansible.verbose = 'vvv'
    ansible.playbook = "provision/playbook.yml"
  end

end
