# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.define "monitor_server"   # guest name used in Ansible groups

  config.vm.box = "rockylinux/9"

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus = 2
    libvirt.qemu_use_session = false
  end

  config.vm.network "private_network", ip: "192.168.124.11"

  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"

  config.vm.provision "ansible" do |ansible|
    ansible.raw_ssh_args = ['-o UserKnownHostsFile=/dev/null']
    ansible.host_key_checking = false
    #ansible.verbose = 'vvv'
    ansible.playbook = "provision/playbook.yml"
  end

end
