# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"
  config.vm.network "private_network", ip: "192.168.124.5"
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.qemu_use_session = false
  end
  config.vm.provision "shell", privileged: true , inline: <<-SHELL
    dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    dnf install -y git docker-ce docker-ce-cli containerd.io docker-compose-plugin
    systemctl enable --now docker
    cd /vagrant
    docker pull quay.io/jupyter/base-notebook:latest
    docker compose up -d
  SHELL
end
