---
- name: Sync Grafana configuration
  ansible.posix.synchronize:
    src: files/etc/grafana
    dest: /etc
  notify: grafana_restart

- name: Create Grafana storage directory
  ansible.builtin.file:
    path: /srv/grafana
    state: directory
    mode: '0755'

- name: Create Grafana components directory
  ansible.builtin.file:
    path: /var/lib/grafana
    state: directory
    mode: '0755'

- name: Grafana container
  containers.podman.podman_container:
    pod: monitoring
    name: grafana
    image: docker.io/grafana/grafana-oss:10.2.6
    volume:
      - /etc/grafana:/etc/grafana:ro
      - /var/lib/grafana:/var/lib/grafana:rw,U,Z
    generate_systemd:
      path: /etc/systemd/system
      restart_policy: on-failure

- name: Enable Grafana container
  ansible.builtin.systemd_service:
    name: container-grafana.service
    daemon_reload: yes
    enabled: true
    state: started

