---
- name: Install dependency packages
  ansible.builtin.dnf:
    name: podman

- name: Create a common pod for monitoring
  containers.podman.podman_pod:
    name: monitoring
    ports:
      - "9090:9090" # Prometheus
      - "3000:3000" # Grafana
    generate_systemd:
      path: /etc/systemd/system
      restart-policy: on-failure

- name: Enable common monitoring pod
  ansible.builtin.systemd_service:
    name: pod-monitoring.service
    daemon_reload: yes
    enabled: true
    state: started
