---
- name: Sync Prometheus configuration
  ansible.posix.synchronize:
    src: files/etc/prometheus
    dest: /etc

- name: Create Prometheus storage directory
  ansible.builtin.file:
    path: /srv/prometheus
    state: directory
    mode: '0755'

- name: Node-Exporter container
  containers.podman.podman_container:
    pod: monitoring
    name: node-exporter
    image: quay.io/prometheus/node-exporter:v1.7.0
    volume:
      - /:/host:ro,rslave

- name: Prometheus container
  containers.podman.podman_container:
    pod: monitoring
    name: prometheus
    image: quay.io/prometheus/prometheus:v2.45.4
    volume:
      - /etc/prometheus:/etc/prometheus:ro
      - /srv/prometheus:/srv/prometheus:rw,U,Z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/srv/prometheus'
