# vi: set ft=ruby :
docker_compose = %q(
version: '3'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europa/Berlin'
      WEBPASSWORD: '12345678'
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      IPv6: 'false'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
)
Vagrant.configure("2") do |config|
  config.vm.define  "pihole"
  config.vm.box = "debian/buster64"
  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # this is only required for the deployment using Docker
  config.vm.provision "shell" do |s|
    s.privileged = true,
    s.inline = %Q(
      apt-get update -q
      apt-get install -q -y docker docker-compose
      echo "#{docker_compose}" > docker-compose.yml 
      docker-compose up --detach
    )
  end
end
EOF
