# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-03-28T10:08:17Z"
  labels:
    app: prometheus
  name: prometheus
spec:
  containers:
  - image: quay.io/prometheus/node-exporter:v1.7.0
    name: node-exporter
    ports:
    - containerPort: 9090
      hostPort: 9090
    securityContext: {}
    volumeMounts:
    - mountPath: /host
      name: root-host-0
      readOnly: true
  - args:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/usr/share/prometheus/console_libraries
    - --web.console.templates=/usr/share/prometheus/consoles
    image: quay.io/prometheus/prometheus:v2.45.4
    name: prometheus-server
    securityContext: {}
    volumeMounts:
    - mountPath: /etc/prometheus
      name: etc-prometheus-host-0
      readOnly: true
    - mountPath: /prometheus,ro=false
      name: srv-prometheus-host-1
    - mountPath: /prometheus
      name: b54e2c57ea2c38acd5d4b296a9b497d5cd4cbb900e37bf4eaeebbdbac1495a61-pvc
  volumes:
  - hostPath:
      path: /
      type: Directory
    name: root-host-0
  - hostPath:
      path: /etc/prometheus
      type: Directory
    name: etc-prometheus-host-0
  - hostPath:
      path: /srv/prometheus
      type: Directory
    name: srv-prometheus-host-1
  - name: b54e2c57ea2c38acd5d4b296a9b497d5cd4cbb900e37bf4eaeebbdbac1495a61-pvc
    persistentVolumeClaim:
      claimName: b54e2c57ea2c38acd5d4b296a9b497d5cd4cbb900e37bf4eaeebbdbac1495a61

