global:
  scrape_interval: 1m
scrape_configs:
- job_name: 'localhost'
  static_configs:
  - targets:
    - localhost:9090
    - localhost:9100
scrape_config_files:
- '/etc/prometheus/scrape_config.d/*.yml'
