# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"
  config.vm.network "private_network", ip: "192.168.124.11"
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.qemu_use_session = false
  end
  config.vm.provision "shell", privileged: true , inline: <<-SHELL
    systemctl disable --now firewalld
    setenforce Permissive
    dnf install -y podman buildah
  SHELL
  config.vm.provision "shell", inline: <<-SHELL
    cd /vagrant
    mkdir -p /etc/prometheus/scrape_config.d /srv/prometheus
    cp prometheus.yml /etc/prometheus
    podman play kube prometheus-pod.yml
  SHELL
end
