- name: install slurmctld package
  ansible.builtin.dnf:
    name: slurm-slurmctld

- name: sync config to /etc/slurm
  ansible.posix.synchronize:
    src: files/etc/slurm
    dest: /etc
  notify: slurmctld_restart

- name: enable/start slurmctld.service
  ansible.builtin.systemd_service:
    name: slurmctld.service
    enabled: true
    state: started

