Vagrant.configure("2") do |config|

  %w(cp1 cp2 cp3 wn1 wn2).each do |node|
    config.vm.define "#{node}" do |config|
      config.vm.hostname = "#{node}"
      config.vm.provider :libvirt do |libvirt|
        libvirt.qemu_use_session = false
        libvirt.cpus = 2
        libvirt.memory = 2048
        libvirt.storage :file, :device => :cdrom, :path => "#{ENV['PWD']}/metal-amd64.iso"
        libvirt.storage :file, :size => '20G', :type => 'raw'
        libvirt.boot 'hd'
        libvirt.boot 'cdrom'
        libvirt.serial :type => "file", :source => {:path => "/tmp/#{node}.log"}
      end
    end
  end

end

