---
- hosts: monitor_server
  become: true
  tasks:
    - ansible.builtin.include_tasks: tasks/monitoring-pod.yml
    - ansible.builtin.include_tasks: tasks/prometheus.yml
    - ansible.builtin.include_tasks: tasks/grafana.yml
