# vi: set ft=ruby :

ollama_binary = "https://github.com/ollama/ollama/releases/download/v0.1.39/ollama-linux-amd64"

ollama_service = "
[Unit]
Description=Ollama Service
After=network-online.target

[Service]
ExecStart=/usr/bin/ollama serve
User=ollama
Group=ollama
Restart=always
RestartSec=3

[Install]
WantedBy=default.target
"

Vagrant.configure("2") do |config|
  config.vm.define "ollama"
  config.vm.box = "rockylinux/9"
  config.vm.hostname = "ollama"
  config.vm.network "private_network", ip: "192.168.124.22"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.qemu_use_session = false
  end
  config.vm.provision "shell", privileged: true , inline: <<-SHELL
    dnf install -y podman buildah
    curl -L #{ollama_binary} -o /usr/bin/ollama
    chmod +x /usr/bin/ollama
    useradd -r -s /bin/false -m -d /usr/share/ollama ollama
    echo "#{ollama_service}" > /etc/systemd/system/ollama.service
    systemctl daemon-reload
    systemctl enable --now ollama.service
  SHELL
end
